# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image_store/', verbose_name='Изображение')),
                ('description', models.CharField(max_length=250, verbose_name='Описание')),
                ('key', models.SlugField(max_length=6, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='Число просмотров')),
                ('upload_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='Загружено')),
                ('last_view_datetime', models.DateTimeField(blank=True, verbose_name='Просмотрено')),
            ],
        ),
    ]
