# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='last_view_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Просмотрено'),
        ),
    ]
