# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0002_auto_20161121_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Число лайков'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Загружено'),
        ),
    ]
