# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0006_auto_20161123_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='file_size',
            field=models.PositiveIntegerField(default=0, verbose_name='Размер файла, Mb'),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Высота, px'),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Ширина, px'),
        ),
    ]
