# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picstore', '0007_auto_20161124_1045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.AlterField(
            model_name='image',
            name='file_size',
            field=models.FloatField(default=0, verbose_name='Размер файла, Mb'),
        ),
    ]
